# Generated by Django 4.0.1 on 2022-01-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('IdProduktu', models.AutoField(primary_key=True, serialize=False)),
                ('NazwaProduktu', models.CharField(max_length=120)),
                ('IloscKalorii', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Przepisy',
            fields=[
                ('IdPrzepisu', models.AutoField(primary_key=True, serialize=False)),
                ('NazwaDania', models.CharField(max_length=128)),
                ('AutorPrzepisu', models.CharField(max_length=120)),
                ('RodzajKuchni', models.CharField(max_length=120)),
                ('Produkty', models.CharField(max_length=12000)),
                ('PrzepisDania', models.TextField(max_length=1200000)),
            ],
            options={
                'verbose_name': 'Przepis',
                'verbose_name_plural': 'Przepisy',
            },
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('IdUzytkownika', models.AutoField(primary_key=True, serialize=False)),
                ('NazwaUzytkownika', models.CharField(max_length=120)),
                ('haslo', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Uzytkownik',
                'verbose_name_plural': 'Uzytkownicy',
            },
        ),
    ]
