# Generated by Django 4.0.1 on 2022-01-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0002_produkty_przepisy_uzytkownicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
