# Generated by Django 4.0.1 on 2022-01-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('przepisy', '0003_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przepisy',
            name='PrzepisDania',
            field=models.TextField(max_length=1200000000),
        ),
    ]
